jaeseo222/Altu-Bitu-3-preparation

09월 02일 - 정렬/선택/11651.cpp

힌트 : 튜터링 때 다룬 응용문제에서 배운 부분을 활용해 볼 수 있겠어요!

[정렬] 선택 11651

---

.gitignore
09월 06일 - 맵과 셋/필수/10757_v1.cpp
09월 06일 - 맵과 셋/필수/10757_v2.cpp

10757_v1.cpp는 vector로, 10757_v2.cpp는 stack으로 풀었습니다.
힌트: 두 수를 그냥 더하기에는 숫자가 너무 커요. 직접 숫자를 더할 때 일의 자리부터 하나하나 더했죠? 그 방식으로 문제를 풀면 좋아요!

[맵과 셋] 필수 10757

---

09월 02일 - 정렬/선택/1026.cpp
09월 02일 - 정렬/선택/[정렬] 선택 1026

Create [정렬] 선택 1026

---

09월 06일 - 맵과 셋/선택/7785.cpp

힌트 : 회사에 남아있는 사람만 누구인지 알면 되겠어요! 그리고 마지막에 역순으로 이름을 출력해야 하네요. set의 기본은 오름차순 정렬이었죠! 역순으로 순환하려면 어떻게 해야 할까요? 의외로 쉬운 방법이 있어요.

[맵과 셋] 선택 7785

---

09월 02일 - 정렬/선택/1431.cpp
09월 09일 - 스택, 큐, 덱/4889.cpp

[힌트] 문자열들을 문제의 조건대로 정렬하기 위해서 compare함수를 직접 만들어봅시다! 문자열의 문자가 숫자인지 알파벳인지는 어떻게 파악할 수 있을까요? 사람들이 이미 방법을 만들어 놨을지도 몰라요!

[정렬] 선택 1431

---

09월 06일 - 맵과 셋/선택/9375.cpp

[힌트]
의상의 이름과 의상의 종류 중 우리에게 필요한 입력값은 무엇일까요?
마지막에 해빈이가 알몸이 되지 않도록 주의해주세요!

[맵과 셋] 선택 9375

---

1213.cpp

[힌트] 앞뒤로 반복되어 나올 알파벳과 가운데에 위치할 알파벳을 분리한다면 펠린드롬을 쉽게 구현할 수 있지 않을까요?

[정수론] 필수 1213

---

09월 02일 - 정렬/선택/1946.cpp
09월 06일 - 맵과 셋/선택/14425.cpp
09월 09일 - 스택, 큐, 덱/1918.cpp

하하,, 제가 모르고 같은 브랜치에 커밋했네요ㅜㅜ
이번 한번만 같은 브랜치에 푸시하겠습니당..🥺🥺
1946 힌트 : 서류심사와 면접심사의 성적을 모두 고려해 동시에 비교하려니 힘드네요. 하나의 심사 순위만 비교하려면 어떻게 해야 할까요? 
14425 힌트 : 문자열을 저장하기 위해서 어떤 자료형을 사용하면 좋을까요? 문자열을 빠르게 탐색할 수 있는 자료형이면 좋겠네요!
1918 힌트 :   후위 표기식에 대해 알아볼까요? 피연산자의 순서는 중위 표기식과 같으니 연산자의 순서를 정하는 게 중요할 것 같아요. 연산자 우선순위를 어떻게 세워야 중위 표기식을 후위 표기식으로 바꿀 수 있을까요?
-> 1918 문제는 처음 맞닥뜨렸을때는 해결 방법을 떠올리기가 어려워서 작년에 해설 자료 pdf(?)를 같이 제공해드렸던 것 같은데 이번에도 제공해드리면 좋을 것 같습니다!!

[정렬] 선택 1946, [맵과 셋] 선택 14425, [스택, 큐, 덱] 1918

---

9월 13일 - 정수론/6588.cpp

힌트
혹시 새로운 수를 입력받을때마다 소수인지 판단하는 과정을 반복하고 있지는 않나요?
두 소수중 하나를 정했다면 나머지 하나는 자동으로 결정 되죠! 
b-a 가 가장 크다는것이 어떤 의미일지 잘 생각해봅시다.

[정수론] 6588

---

9월 13일 - 정수론/선택/20302.cpp

힌트 : 연산은 *와 / 밖에 없네요! 연산한 최종 결과로 판단하지 않고, 과정에서 판단할 수 있는 방법이 없을까요? 수는 분해가 가능하죠.
😍😍😍

[정수론] 선택 20302

---

09월 16일 - 브루트 포스/선택/1038_queue.cpp

**[힌트]** 한 감소하는 수에서 어떻게 다른 감소하는 수를 얻을 수 있을까요? 맨 끝에 자릿수를 하나씩 추가하다 보면 감이 올거에요. 그리고 감소하는 수의 최대값이 어떤 수인지도 생각해 봐요.
찾아보니까 이 문제가 dp, dfs/bfs 등등 정말 다양한 방법으로 풀 수 있는 문제더라구요,,,! 일단 dp나 그래프 관련은 아직 배우지 않았으니 그런 방법들은 최대한 배제하고 코드를 짰는데 어떨지 모르겠어요...문제를 잘못고른거 같기도 하고.....ㅠㅠ
끝자리에 숫자 하나씩 추가하는 방법으로 풀려면 큐, 재귀 이렇게 크게 두가지가 가능한데, 재귀보단 큐가 더 효율적일것 같아서 일단 큐로만 샘플코드 작성했는데 혹시 재귀 버젼으로도 만들어 놓을까요...?
그리고 힌트에서 자릿수 추가하는 부분이 너무 직접적이면 알려주세요!! 수정하겠습니다

[브루트포스] 선택 1038

---

9월 13일 - 정수론/14490.cpp

[힌트]
입력을 문자열로 받아볼까요? 어떻게 하면 문자열을 정수로 변환할 수 있을까요?

[정수론] 14490

---

09월 20일 - 구현 & 코너케이스/선택/19636.cpp

[힌트]
문제를 꼼꼼히 읽으며 필요한 연산을 찾아보아요. 음수의 나눗셈 처리를 주의해주세요!

[구현&코너케이스] 선택 19636.cpp

---

09월 16일 - 브루트 포스/선택/16420.cpp

힌트 : 그래프의 크기가 최대 10 x 10 이네요? 세개의 꽃을 심을 수 있는 모든 경우의 수를 탐색해보아도 괜찮겠어요.  꽃이 피는 자리가 그래프의 테두리에 있는 경우는 없네요.
씨앗을 다 심었다면 특정 위치에 씨앗을 심을 경우 5칸의 비용이 얼마인지를 알아야하고, 또 그렇게 씨앗을 심었을때 꽃잎이 죽지 않는지를 판단해야해야겠네요! 
힌트는 어떤 것을 함수화하면 좋을지 알아차릴 수 있도록 구성해봤어용! 그리구.. 아래는는 제가 예전에 풀었던 풀이과정 적어놓은 링크인데,, 괜찮으시다면 같이 제공해드리겠습니다! 사실 별거 없어여 핳..ㅎㅎ
https://flowersayo.tistory.com/80 <-

[브루트포스] 선택 14620

---

09월 20일 - 구현 & 코너케이스/필수/2840.cpp

힌트: 바퀴에 같은 글자가 두 번 등장하거나, 중복되는 글자가 있으면 안 돼요!!
+) 바퀴를 고정시키고 화살표의 위치를 바꾸는 식으로 문제를 풀면, 출력시에는 방향을 바꿔서 출력해야해요.

[구현 & 코너케이스] 필수 2840

---

09월 20일 - 구현 & 코너케이스/선택/1316.cpp

힌트 : 이 알파벳이 이전에도 등장했었는지 효율적으로 판단할 수 있는 방법이 없을까요? 알파벳은 26개밖에 없네요! (배열을 활용해볼까요?)

[구현&코너케이스] 선택 1316

---

09월 23일 - 백트래킹/선택/10971.cpp

[힌트]
일단 방문할 수 있는 도시를 차례차례 방문해볼까요? 출발 도시로 다시 돌아왔다면 가는 길을 알게 된 거네요! 어느 곳에서 출발해도 똑같겠어요.

[백트래킹] 10971

---

09월 23일 - 백트래킹/선택/2580.cpp

[힌트] 빈칸이 아니면 다음 칸으로 넘어가고, 빈칸인 경우에는 가능한 숫자를 차례대로 넣어보고 안되면 다른 숫자를 넣어보도록 해요! 그리고 숫자들이 같은 3x3 정사각형 안에 있는지 아닌지는 어떻게 알아낼 수 있을까요? 풀이 방향을 잘 모르겠다면  N-queen 문제랑 비슷하게 접근하면 될 것 같네요!

[백트랙킹] 선택 2580

---

09월 27일 - 동적 계획법/필수/20055_v1.cpp
09월 27일 - 동적 계획법/필수/20055_v2.cpp

[힌트] 벨트의 회전과 로봇의 이동을 인덱스로 관리해볼까요?
> 지난번에 제공해주셨던 코드 바탕으로 2단계 while문으로 수정하고 함수명만 조금 수정했습니다!

[동적계획법] 필수 20055

---

09월 27일 - 동적 계획법/필수/20923.cpp

힌트) 둘 중 한 명이 2~4번까지의 과정을 진행하는 것을 1번 진행한 것으로 보는 것과
게임 진행 도중 자신의 덱에 있는 카드의 수가 0개가 되는 즉시 상대방이 승리하는 것을 주의하세요
힌트를 뭘 줘야 될 지....문제를 잘 읽어보세요! 이렇게 할 수 도 없고요!!ㅠㅠ

[동적계획법] 필수 20923

---

09월 30일 - 우선순위 큐/선택/1927.cpp

[힌트] C++에서 우선순위 큐의 디폴트가 어떤 힙이었는지 생각해 보면 아주 쉬울 거에요. 만약 감이 안온다면, 정렬을 다룰 때 디폴트와 반대인 정렬을 쉽게 할 수 있던 함수를 떠올려 봐요!

[우선순위 큐] 선택 1927

---

09월 27일 - 동적 계획법/선택/2156.cpp

힌트 : 현재 잔을 기준으로 선택할 수 있는 잔의 방법을 생각해볼까요~?!

[동적계획법] 선택 2156

---

09월 23일 - 백트래킹/선택/15663.cpp

힌트 : 우선 기본 구조는 N과 M(1) 과 크게 다르지 않아보여요! 그런데 제공해주는 집합의 원소들이 중복될 수도 있네요!
어떻게 해야 수열의 중복을 피할 수 있을까요? 바로 이전에 선택된 값을 저장해볼까요?

[백트래킹] 선택 15668 

---

09월 23일 - 백트래킹/선택/17255.cpp

힌트 : 어떤 수 N이 이미 적혀있고, 이 위를 가리는 블록을 왼쪽, 오른쪽으로 하나씩 제거해서 숫자를 드러낸다고 생각해 볼까요? 그리고 중복되는 방법을 거르기 위해 과정을 저장해야겠어요.
🔥🔥🔥

[백트래킹] 선택 17255

---

09월 27일 - 동적 계획법/선택/9084.cpp

힌트 : 한번에 M원을 만들 수 있는 방법의 수를 세는 건 어려워요. 최종 M원을 만들어가는 금액마다 동전으로 만들 수 있는 방법의 수를 세어볼까요?
늦어서 죄송합니다!! 😂😂

[동적계획법] 선택 9084

---

09월 30일 - 우선순위 큐/선택/23757.cpp

[우선순위큐] 선택 23757

---

09월 27일 - 동적 계획법/선택/11053.cpp

힌트 :  동적계획법 강의자료 피피티를 꼼꼼히 살펴볼까요?

[동적계획법] 11053

---

10월 04일 - 그리디 알고리즘/선택/10610.cpp

[힌트]
문제 풀이에 대한 힌트를 제공할 지 입출력에 대해 힌트를 제공할 지 고민입니다ㅜㅜ
문제 풀이에 대해서는 오히려 빨리 생각할 수 있을 것 같은데 실제로 제출 시에 많이 놓치는 부분이 입출력인 것 같아서요...!
-> 30의 배수인지 어떻게 확인할 수 있을까요?
-> 입력의 크기가 어떻게 되는지 확인해보세요!
의견 주시면 감사하겠습니다!
----------------------
[힌트 최종!!]
30의 배수인지 어떻게 확인할 수 있을까요? 그리고 입력의 크기가 어떻게 되는지 확인해보세요!

[그리디] 선택 10610

---

10월 04일 - 그리디 알고리즘/선택/11000.cpp

힌트: 시작 시간과 종료 시간 중 무엇을 더 먼저 고려해야 할까요? 시간이 빠른 순서대로 강의를 배치하는 것이 중요할 것 같은데 어떤 자료구조를 사용하는 것이 좋을까요?
주석이 조금 불친절한 것 같기도 해서 필요하다면 추가할게요!!

[그리디 알고리즘] 선택 11000

---

09월 30일 - 우선순위 큐/선택/1966.cpp

[힌트]
가장 높은 수의 중요도부터 순서대로 비교하기 위해선 어떤 자료형을 사용하는게 좋을 까요?

[우선순위 큐] 1966

---

09월 30일 - 우선순위 큐/선택/19638.cpp

힌트 : 센티의 전략을 잘 살펴볼까요? 항상 키가 큰 사람이 뿅망치를 맞겠네요!
🦕🦕🦕

[우선순위 큐] 선택 19638

---

09월 30일 - 우선순위 큐/선택/2075.cpp

힌트: 모든 수를 저장하기에는 메모리가 부족해요! 입력을 받으면서, 의미있는 수들만 남겨놓고 나머지는 삭제시켜야겠네요. 
N번째 큰수에 접근할 수 있는 자료구조로 무엇을 선택해야 할까요?

[우선순위큐] 선택 2075

---

10월 04일 - 그리디 알고리즘/선택/2437.cpp

힌트
이미 잴 수 있는 무게가 있다면, 새로운 추가 생겼을 때 잴 수 있는 무게의 범위는 어떻게 달라질까요?

[그리디 알고리즘] 선택 2437

---

10월 14일 - DFS & BFS/선택/11725.cpp

힌트 : 탐색 시작 위치를 잡는 것이 중요해요. 두 노드 중 어떤 노드가 부모노드인지 구분하기 위해서는 어떤 노드부터 탐색을 시작해야 할까요?
하핫 😁

[DFS & BFS] 선택 11725

---

10월 04일 - 그리디 알고리즘/필수/3613.cpp

힌트: 예외처리를 정말 잘 해줘야 하는 문제에요. 마지막 문자가 _가 아니어야 하고, _가 연속으로 나오면 안 된다는 것을 잊지 맙시다!! 그리고 Java와 C++ 모두에 해당하는 변수도 있지 않을까요?
이거 주의사항이 4가지 정도 되는데, 이 중에 2가지만 말해줘도 되겠죠...? (힌트 고르기가 어렵네요ㅠㅠ)
@kwakrhkr59

[그리디 알고리즘] 필수 3613

---

10월 14일 - DFS & BFS/선택/1012.cpp
10월 14일 - DFS & BFS/선택/1012_bfs.cpp

HINT
구역을 지정하기 위해 방문했던 곳은 다시 방문하면 안될 것 같아요!

[DFS&BFS] 선택 1012

---

10월 07일 - 이분 탐색/선택/3079.cpp

HINT
시간의 최소값을 찾는 문제네요! 상근이가 어떤 시간을 찾고 싶은 건지 생각해보세요! 또 상근이의 친구가 굉장히 많아보이고 심사시간도 긴 것 같아요!

[이분탐색] 선택 3079

---

10월 07일 - 이분 탐색/선택/17266.cpp

[힌트]
설정한 가로등 높이가 모든 구간을 밝힐 수 있는지 구간마다 확인해볼까요?

[이분탐색] 선택 17266

---

10월 11일 - 투 포인터/필수/7662.cpp
10월 11일 - 투 포인터/필수/7662_v1.cpp
10월 11일 - 투 포인터/필수/7662_v2.cpp

[힌트] 우선순위 큐를 활용해 최솟값을 뽑아볼까요? 최댓값과 최솟값을 따로 관리해주려면 해당 원소가 몇 개가 남았는지도 알아둬야겠어요!
전에 파이썬으로 풀었던 걸 c++로 바꾼 건데 지난 기수 샘플코드만큼 효율적으로 만들기는 어렵더라고요ㅜㅜ 이번 기수에는 어떤 걸 샘플로 드려야 할지 고민입니다😂

[투포인터] 필수 7662

---

10월 11일 - 투 포인터/선택/20437.cpp

힌트: 각 문자의 개수가 중요할 것 같아요. 문자의 위치를 알면 둘 사이의 거리도 알 수 있겠네요.

[투 포인터] 선택 20437

---

10월 04일 - 그리디 알고리즘/필수/2503.cpp

힌트) 서로 다른 세 자리 수 중에 최대 수는 무엇이죠? 모든 경우를 다 해봐도 좋겠어요. 0은 사용하지 않는다는 걸 주의해야 해요.
힌트가 좀 더 구체적이면 좋을까요??숫자 111~999까지 하나하나 살펴보세요!이게 더 나을까요?
코드 중간에 있는 문제 설명은 전에 기수꺼 그대로 가져왔습니다.
문자열로 안 하고 몫,나머지로 하는 풀이가 있더라구요. 그게 더 괜찮을 지 모르겠어요..밑에 코드 첨부합니다(제 코드 아니에요)
`#include <stdio.h>
int main()
{
int bbc, ssc, cnt, n, i, j, S[105], B[105], Q[105];
int a, b, c, aa, bb, cc, result = 0;
scanf("%d", &n);
for (i = 0; i < n; i++)
{
scanf("%d %d %d", &Q[i], &S[i], &B[i]);
}
for (i = 100; i <= 999; i++)
{
a = i / 100;
b = i % 100 / 10;
c = i % 10;
if (a == b || b == c || a == c || b == 0 || c == 0)
continue;
cnt = 0;
for (j = 0; j < n; j++)
{
ssc = 0;
bbc = 0;
aa = Q[j] / 100;
bb = Q[j] % 100 / 10;
cc = Q[j] % 10;
if (a == aa)
ssc++;
if (b == bb)
ssc++;
if (c == cc)
ssc++;
if (a == bb || a == cc)
bbc++;
if (b == aa || b == …

[그리디 알고리즘]필수 2503

---

10월 11일 - 투 포인터/필수/1244.cpp

[투포인터]필수 1244

---

10월 07일 - 이분 탐색/선택/17053.cpp

힌트 : 이분탐색을 통해 특정 도수 레벨이 되었다고 가정해볼까요? 현재 도수레벨이 너무 낮아서 마실 수 있는 맥주 수가 n개가 되지 않는다면 도수레벨을 증가시키고, 현재 도수레벨이 너무 높아서 선호도가 m보다 작다면 도수레벨을 다시 감소시키면 되겠죠!

[이분탐색] 선택 17503

---

10월 07일 - 이분 탐색/선택/16401.cpp

[힌트] 과자조각의 최대 길이를 이분탐색으로 변화시키면서, 최대길이만큼 만들 수 있는 과자 조각 수가 얼마인지 생각해 봐요! 과자 조각 수가 어떨 때에 조카들에게 과자를 나눠 줄 수 있을까요?

[이분탐색] 선택 16401

---

11월 01일 - 최단 경로/선택/10282.cpp

힌트: 감염 방향을 잘 고려해야겠어요. 가장 마지막 노드가 감염되는 최소 시간을 어떻게 구할 수 있을까요?

[최단 경로] 선택 10282

---

11월 01일 - 최단 경로/선택/taxi.cpp

힌트 : 함께 합승할 수 있는 지점은 총 몇 개인가요? 계산에 고려해야 할 가능한 시작, 도착 지점의 쌍이 어떻게 될까요?
🤩🤩

[최단 경로] 선택 합승 택시 요금

---

11월 01일 - 최단 경로/필수/3085.cpp

힌트: 범위가 크지 않으니 바꿀 수 있는 사탕을 하나하나 다 바꿔봐도 좋아요. 각 행과 열에서 먹을 수 있는 사탕의 수를 세는게 중요하겠네요.

[최단 경로] 필수 3085

---

11월 01일 - 최단 경로/필수/16235.cpp

힌트) deque 컨테이너를 활용해서 어린 나무부터 순서대로 저장해보아요

[최단경로] 필수 16325

---

11월 08일 - 구현 & 코너케이스/선택/2607.cpp

힌트: 단어가 일치하는지 확인하는 게 아니라 구성을 비교해야 해요. 꽤 자주 말한 것 같지만, 알파벳은 겨우 26개입니다! 문자를 빼거나 더하거나, 바꿀 수 있네요. 두 단어에서 서로 다른 문자의 개수에 집중해볼까요?

[구현&코너케이스] 선택 2607

---

11월 08일 - 구현 & 코너케이스/선택/17503.cpp

힌트 : 문제의 조건을 정확하게 이해하는 것이 중요해요. 애매한 부분이 생겼다면 [링크](https://www.acmicpc.net/board/view/96605) 를 참고해볼까요?

[구현&코너케이스] 선택 14503

---

11월 15일 - 트리/필수/18111.cpp

힌트: 우리에게는 처음부터 제공되는 블록도 있지만, 다른 곳에서 블록을 가져올 수도 있어요. 참고로 가능한 모든 높이에 대해 브루트포스 연산을 해도 시간 초과가 나지 않아요~

[트리] 필수 18111

---

11월 22일 - 유니온 파인드/선택/4195.cpp

**HINT**
어떤 집합의 원소의 개수를 구하는 익숙한 문제네요! 기존 함수를 그대로 사용할 수 있으면 좋을 것  같은데 정점의 타입이 조금 달라 보여요! 새로운 타입의 정점과 기존에 사용하던 정점의 형식의 관계를 만들어 줄 수 있는 자료구조는 무엇일까요?

[유니온 파인드] 선택 4195

---

11월 15일 - 트리/선택/14675.cpp

힌트 : 입력으로 들어오는 것은 **트리**라고 했죠! 트리는 그래프와 다르게 어떤 특징을 지니고 있나요?

[트리] 선택 14675

---

11월 15일 - 트리/선택/15681.cpp

저는 map으로 tree 구현해서 풀었는데 2기 코드가 훨씬 효율적이고 깔끔한 것 같아서 2기 코드에 주석만 조금 수정했습니다..!
힌트: 각 서브트리의 노드의 수를 저장해두면 한번에 구할 수 있을 것 같아요. 어떤 방법을 이용하면 좋을까요?

[트리] 선택 15681

---

11월 15일 - 트리/선택/5639.cpp
11월 15일 - 트리/선택/5639v2.cpp

힌트 : 전위 순회로 입력 받은 값을 어떻게 후위 순회로 출력할 수 있을까요?

[트리] 선택 5639

---

11월 15일 - 트리/선택/1967.cpp

힌트 : 지름을 이루는 두 정점을 동시에 찾을 순 없어요. 임의의 모든 정점에서 가장 멀리 있는 정점들은 어떤걸까요? 그 정점들엔 어떤 공통점이 있나요? 지름의 길이를 구하려면 자식->부모 방향으로 거슬러 올라가야 할 수도 있겠어요. 그림에 힌트가 아주 많아요!

[트리] 선택 1967

---

11월 15일 - 트리/필수/11559.cpp

힌트!)
뿌요가 터지는 상황을 생각해봅시다! 터진 이후에는, 빈칸이 생기고 위에 있는 뿌요가 밑으로 내려와야겠죠? 한 줄에 여러 개가 터질 수 있으니, 비어있는 칸이 아닌 남아있는 뿌요들만 모아서 다음 단계에 사용할 수 있어요. 그런데, 입력을 그대로 받으면 열을 기준으로 계산해야 합니다. 구현을 편하게 하기 위해서 어떻게 할 수 있을까요?

[트리] 필수 11559

---

11월 22일 - 유니온 파인드/선택/1043.cpp

힌트 : 같은 파티에 속한 사람들은 하나의 집합에 속해 있다고 할 수 있겠네요. 진실을 말할 수 없는 경우는 그 집합이 어떤 상태일 때 일까요? 라이브 코딩에서 다룬 4803번에서 힌트를 구할 수 있어요! 한 사람이 여러 파티에 참여할 수 있다는 걸 잊으면 안돼요.

[유니온 파인드] 선택 1043

---

11월 15일 - 트리/선택/2533.cpp

트리 선택 2533번 입니다..!
만약 현재 정점이 얼리어답터가 아니라면, 연결되어 있는 정점들은 모두 얼리어답터여야 하겠네요! 해당 정점이 얼리어답터 일 때와 아닐 때의 경우로 나누어 생각해보아요.

[트리] 선택 2533

---

11월 08일 - 구현 & 코너케이스/필수/17281.cpp

[힌트] 입력이 그렇게 크지 않네요! 모든 경우의 수를 다 해보면 될 것 같아요. 3아웃이 되면 아웃 카운트와 출루한 주자들이 모두 리셋되고 새로운 이닝이 시작된다는 규칙을 잘 기억해주세요!
백트래킹을 사용했는데 작년 1번 풀이랑 거의 똑같아지더라구요😂 힌트는 작년 힌트에 야구 규칙 추가해서 작성했습니다! 비트마스킹 사용한 풀이도 이번에도 같이 제공해드리면 좋지 않을까 싶습니다..!

[구현&코너케이스] 필수 17281

---

11월 22일 - 유니온 파인드/필수/양궁.cpp

[힌트] n의 범위가 매우 작아요! 라이언이 주어진 화살로 과녁을 맞추는 모든 경우를 다뤄볼 수 있겠어요. 각 과녁에 대해 라이언이 이기는 경우와 그렇지 않은 경우를 생각해볼까요? 마지막으로, 차이가 동점인 경우 낮은 점수를 더 많이 맞힌 경우를 선택하는 부분을 잘 처리해야 해요. 탐색에 따라 단순 갱신해줘선 안돼요. 따로 조건 처리를 해볼까요?
늦어져서 죄송합니다ㅜ 힌트는 이미 작년 걸로 업로드해주시기도 했고 작년 힌트에서 문제에서 중요한 조건을 잘 짚어주셔서 일단은 그대로 가져왔습니다!
maxDiff랑 answer를 갱신할 때 일일이 인자로 넘겨주는 것보다 전역변수로 선언하는 게 조금 더 깔끔한 것 같아 일단은 그대로 두었는데 인자로 넘겨주는 게 나을지 고민 중입니다..!

[유니온파인드] 필수 양궁

---

11월 22일 - 유니온 파인드/선택/hotelRoom.cpp

힌트 : 시간초과가 발생하나요? 호텔방 번호가 정렬될 필요는 없으니 map보다 탐색이 더 빠른 container를 사용하는 것이 좋겠네요! c++의 map은 트리 구조로 이루어져 있어 시간복잡도가 O(logN)만큼 든다고 했었죠~ 이때, 시간복잡도가 O(1)만큼 드는 구조로 이루어진 map에 대해서도 소개해드렸는데 한 번 찾아볼까요?
마지막 힌트가 너무 직접적인 느낌이 있어 넣을지 말지 고민중입니다..!

[유니온파인드] 선택 호텔방배정

---

11월 29일 - 최소 신장 트리/필수/1744.cpp

힌트: 일단 큰 수끼리는 묶는 게 좋아 보여요. 그리고 음수도 묶으면 수를 키울 수 있는 방법이 보이네요. 이때, 서로 곱하면 더 손해인 수와, 서로 곱해야 더 이득인 수를 잘 파악해서 어디까지 수를 묶는 게 좋은지 범위를 잘 설정해야 해요.
---
+) 질문 들어올 경우 참고할 반례 링크 : https://www.acmicpc.net/board/view/65431

[최소 신장 트리] 필수 1744

---

11월 22일 - 유니온 파인드/선택/20040.cpp

[힌트] 사이클이 언제 생겼는지 알기 위해서는 매번 사이클 발생 여부를 확인해야해요! 그리고 유니온 파인드에서 집합을 합치는 과정에 힌트가 있을 것 같아요!

[유니온파인드] 선택 20040

---

11월 22일 - 유니온 파인드/선택/20303.cpp

유니온파인드 코드가 올라갔다 착각해서 준비가 늦었습니다ㅠ

[유니온파인드] 20303.cpp

---

11월 29일 - 최소 신장 트리/선택/1774.cpp

힌트: 이미 존재하는 통로가 있네요. 그냥 연결해도 될까요? 연결하려고 한 통로가 이미 연결되어있는 통로라면 어떻게 될까요?

[최소 신장 트리] 선택 1774

---

11월 29일 - 최소 신장 트리/필수/16236.cpp

전에 기수꺼에요 :) 최고!
힌트) 상어가 먹을 물고기를 어떤 방법으로 찾아야 할까요? 먹을 수 있는 물고기가 여러 마리일 때는 어떻게 해야 할까요? 상어가 이동할 곳만 잘 찾으면 나머지는 어렵지 않아요. 입력이 정말 작으니 그 어떤 방법을 써도 괜찮아요.

[최소신장트리] 필수 16236

---

12월 06일 - 위상 정렬/선택/1766.cpp

힌트 : 튜터링때 위상정렬은 여러 결과가 나올 수 있다고 했어요. 그런데 해당 문제는 순서에 대한 조건이 있네요! 어떻게 관리하면 좋을까요?
😁😁

[위상 정렬] 선택 1766

---

11월 29일 - 최소 신장 트리/선택/1647.cpp

힌트 : 간선의 합이 최소가 되도록 모든 도시를 연결하는 방법은 너무 잘 알고 있죠! 이 상태에서 비용을 최소로 하면서 두개의 마을로 분리하려면 어떻게 하면 좋을까요? 모든 도시가 연결된 상태라면, 그 중 하나의 간선만 끊어도 도시가 두개로 분리돼죠!

[최소신장트리] 선택 1647

---

12월 06일 - 위상 정렬/필수/13422.cpp

힌트) 훔쳐야 하는 집의 수가 고정됐는데 집이 원형이네요. 훔친 돈이 k보다 작은지 생각해보기 전에...도둑질을 할 수 있는 경우의 수는 어떻게 되나요? 만약 전체 집의 수와 훔쳐야 하는 집의 수가 같다면요?
힌트 전에 기수 재활용했습니다. 👍 👍 
저는 누적합으로 풀었는데
전 기수꺼 코드가 더 좋은 것 같아서 말씀하시면 코드 바꾸도록 하겠습니다.

[위상 정렬] 필수 13422

---

12월 06일 - 위상 정렬/선택/2623.cpp

[힌트]가수들의 순서를 배치하는 건 배운 알고리즘을 쓰면 쉽게 구할 수 있겠어요. 그런데 어떤 경우에 순서를 정하는 것이 불가능할까요? 탐색 과정에서 더 이상 탐색할 정점이 없는 순간이 생긴다는 것일텐데, 이럴 경우에 정렬 결과가 어떻게 나올까요?

[위상정렬] 선택 2623

---

12월 06일 - 위상 정렬/필수/기둥과보설치.cpp

[힌트] 구조물의 설치 조건을 잘 확인해주세요! 구조물을 삭제하기 위한 조건을 일일이 나누기 어렵다면, 반대로 구조물이 삭제됐을 때 원래 붙어있던 다른 구조물이 유지될 수 있을지 확인해주면 어떨까요?

[위상 정렬] 필수 기둥과 보 설치

---

12월 06일 - 위상 정렬/선택/2637.cpp

각 부품마다 필요한 부품을 저장하는 것이 중요해요. 중간 부품의 개수가 아닌 기본 부품의 개수를 저장해야 한다는 걸 주의해야 해요. 어떤 부품이 기본 부품이 될까요?

[위상정렬] 선택 2637
